### ISSUE TITLE
Deferred resolving doesn't seem to work

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/graphql-php#336]
There's something wrong with it. In the test we end up calling `loadBuffered()` twice, which shouldn't happen. There's also both `$directorIds` and `$authors`, which seems wrong. Gotta look this through carefully.

**Comment by Jalle19** [comment]
Related to https://github.com/digiaonline/graphql-php/issues/320

**Comment by crisu83** [comment]
@Jalle19 I took a look at this and you're right. The issue is that the promise is resolved immediately. I need to do some research. It might be that we need to introduce our own Deferred concept, like they have done in Webonyx implementation. I don't like the idea, but if it that's what it takes then we'll do that.

**Comment by inanc-g** [comment]
Any news on this?

**Comment by Jalle19** [comment]
@crisu83 do you have time to look into this?

**Comment by Jalle19** [comment]
or @hungneox

**Comment by acelot** [comment]
Confirm this issue. `loadBuffered()` is called everytime.

**Comment by acelot** [comment]
Guys, this issue is critical for production use. Do you have any suggestions? If you do not have time, tell me which way to dig?

**Comment by asheliahut** [comment]
This is literally the only reason I haven't swapped to this over my Youshido Fork.

**Comment by crisu83** [comment]
@acelot I have my hands full right now with work, but the easiest way to look at it is to debug the deferred resolver test cases. The main issue is that I think that this is related to how we're handling promises when executing them. CC @hungneox

**Comment by asheliahut** [comment]
Is there any thought to use https://github.com/overblog/dataloader-php
to solve the problem like almost everyone in node does?

**Comment by acelot** [comment]
I'm trying to adapt this library for my reactphp-project. I was able to perform a deferred request using [lordthorzonus/php-dataloader](https://github.com/lordthorzonus/php-dataloader). But for this I had to change the graphql-php code to support async calls. Because the existing executor have a race condition problem [`Execution::execute()`](https://github.com/digiaonline/graphql-php/blob/master/src/Execution/Execution.php#L55):

```php
if ($data instanceof PromiseInterface) {
    $data->then(function ($resolvedData) use (&$data) {
        $data = $resolvedData;
    });
}

<...>

return new ExecutionResult($data, $context->getErrors());
```

In this section of the code, the `$data` variable will always be `null` and will throw an exception.
To add support for asynchronous calls, I suggest adding a new method `promiseExecute`:

```php
class Execution implements ExecutionInterface, PromisedExecutionInterface
{
    public function promiseExecute(
        Schema $schema,
        DocumentNode $documentNode,
        $rootValue = null,
        $contextValue = null,
        array $variableValues = [],
        ?string $operationName = null,
        ?callable $fieldResolver = null,
        ?ErrorHandlerInterface $errorHandler = null
    ): PromiseInterface {
        <...>

        if ($data instanceof PromiseInterface) {
            return $data->then(function ($resolvedData) use ($context) {
                return new ExecutionResult($resolvedData, $context->getErrors());
            });
        }

        <...>

        return resolve(new ExecutionResult($data, $context->getErrors()));
    }
}
```

I can provide PR, but I need help with tests.

**Comment by Jalle19** [comment]
@acelot PRs are more than welcome, I'll help you out with the tests!

**Comment by acelot** [comment]
@Jalle19 #345

**Comment by crisu83** [comment]
@acelot is this issue resolved?

**Comment by acelot** [comment]
Yes, completely.
